In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
## imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
## Solving two prolems the - 
##    trying to predict the exited   -  Classification Problem
##    trying to predict the estimated salary - Regression Problem
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Classification - Predicting Exited

In [4]:
## Dividing Dataset into inputs(x) and outputs(y)
X = dataset.iloc[:,3:13]
y = dataset.iloc[:, 13]

In [5]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [6]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [7]:
# Feature Engineering
geography = pd.get_dummies(X["Geography"], drop_first=True) # Since there are two location Germany and France it will create a Germany column which will be binary meaning that if its 0 or false then the location has to be France.
gender = pd.get_dummies(X["Gender"], drop_first=True)

In [8]:
X = X.drop(["Geography", "Gender"], axis=1)

In [9]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57  
3               0         93826.63  
4               1         79084.10

In [10]:
X = pd.concat([X, geography, gender], axis=1)

In [11]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0                  1        101348.88        0      0     0  
1                  1        112542.58        0      1     0  
2                  0        113931.57        0      0     0  
3                  0         93826.63        0      0     0  
4                  1         79084.10        0      1     0  
...              ...              ...      ...    ...   ...  
9995               0         96270.64        0      0     1  
9996               1        101699.77        0      0     1  
9997               1         42085.58        0      0     0  
9998               0         92888.52        1      0     1  
9999               0         38190.78        0      0     0  

[10000 rows x 11 columns]

In [12]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [13]:
#feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [15]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [16]:
# Creating the ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [17]:
classifier=Sequential()

In [18]:
classifier.add(Dense(10,input_shape=(11,),activation='relu')) # Input Layer

In [19]:
classifier.add(Dense(units=10,activation='relu')) # Hidden Layer 1

In [20]:
classifier.add(Dense(units=10,activation='relu')) # Hidden Layer 2

In [21]:
classifier.add(Dense(1,activation='sigmoid')) # Output Layer

In [22]:
classifier.summary() # Model Summary

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                120       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 10)                110       
                                                                 
 dense_3 (Dense)             (None, 1)                 11        
                                                                 
Total params: 351
Trainable params: 351
Non-trainable params: 0
_________________________________________________________________


In [23]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [24]:
classifier.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy']) # Compiling the Model

In [25]:
## Early Stopping
import tensorflow as tf
early_stopping=tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5
)

In [26]:
model_history= classifier.fit(X_train, y_train, validation_data=(X_test,y_test), batch_size=10, epochs=10, callbacks=early_stopping)

Epoch 1/10
800/800 [==============================] - 3s 2ms/step - loss: 0.4275 - accuracy: 0.8136 - val_loss: 0.3787 - val_accuracy: 0.8505
Epoch 2/10
800/800 [==============================] - 2s 2ms/step - loss: 0.3599 - accuracy: 0.8521 - val_loss: 0.3594 - val_accuracy: 0.8480
Epoch 3/10
800/800 [==============================] - 2s 2ms/step - loss: 0.3562 - accuracy: 0.8571 - val_loss: 0.3498 - val_accuracy: 0.8565
Epoch 4/10
800/800 [==============================] - 2s 2ms/step - loss: 0.3517 - accuracy: 0.8568 - val_loss: 0.3582 - val_accuracy: 0.8490
Epoch 5/10
800/800 [==============================] - 2s 3ms/step - loss: 0.3506 - accuracy: 0.8589 - val_loss: 0.3529 - val_accuracy: 0.8550
Epoch 6/10
800/800 [==============================] - 2s 2ms/step - loss: 0.3482 - accuracy: 0.8584 - val_loss: 0.3484 - val_accuracy: 0.8575
Epoch 7/10
800/800 [==============================] - 2s 2ms/step - loss: 0.3476 - accuracy: 0.8601 - val_loss: 0.3653 - val_accuracy: 0.8550
Epoch 

In [27]:
classifier.save_weights("model.h5")

# Regression - Predicting Estimated Salary

In [28]:
# Input and Output Features for Regression
X=dataset[['CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember','Exited']]
y=dataset.iloc[:,12]

In [29]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  Exited  
0          1               1       1  
1          0               1       0  
2          1               0       1  
3          0               0       0  
4          1               1       0

In [30]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...    
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [31]:
# Feature Engineering
geography = pd.get_dummies(X["Geography"], drop_first=True) # Since there are two location Germany and France it will create a Germany column which will be binary meaning that if its 0 or false then the location has to be France.
gender = pd.get_dummies(X["Gender"], drop_first=True)

In [32]:
X = X.drop(["Geography", "Gender"], axis=1)

In [33]:
X = pd.concat([X, geography, gender], axis=1)

In [34]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [35]:
#feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [38]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [39]:
# Creating the ANN Regressor
regressor=Sequential()

In [40]:
regressor.add(Dense(10,input_shape=(11,),activation='relu'))

In [41]:
regressor.add(Dense(units=10,activation='relu'))

In [42]:
regressor.add(Dense(units=10,activation='relu'))

In [43]:
regressor.add(Dense(1))

In [44]:
regressor.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 10)                120       
                                                                 
 dense_5 (Dense)             (None, 10)                110       
                                                                 
 dense_6 (Dense)             (None, 10)                110       
                                                                 
 dense_7 (Dense)             (None, 1)                 11        
                                                                 
Total params: 351
Trainable params: 351
Non-trainable params: 0
_________________________________________________________________


In [48]:
mse=tf.keras.losses.MeanSquaredError(
    name='mean_squared_error'
)

In [49]:
regressor.compile(optimizer=opt,loss=mse,metrics=['mae']) # Compiling the Regressor

In [50]:
model_history= classifier.fit(X_train, y_train, validation_data=(X_test,y_test), batch_size=10, epochs=10, callbacks=early_stopping)

Epoch 1/10
800/800 [==============================] - 3s 3ms/step - loss: -2902930227200.0000 - accuracy: 0.0000e+00 - val_loss: -10715469447168.0000 - val_accuracy: 0.0000e+00
Epoch 2/10
800/800 [==============================] - 2s 3ms/step - loss: -32439179149312.0000 - accuracy: 0.0000e+00 - val_loss: -62102391750656.0000 - val_accuracy: 0.0000e+00
Epoch 3/10
800/800 [==============================] - 3s 3ms/step - loss: -112614671646720.0000 - accuracy: 0.0000e+00 - val_loss: -172577859305472.0000 - val_accuracy: 0.0000e+00
Epoch 4/10
800/800 [==============================] - 3s 3ms/step - loss: -260539527725056.0000 - accuracy: 0.0000e+00 - val_loss: -358642553454592.0000 - val_accuracy: 0.0000e+00
Epoch 5/10
800/800 [==============================] - 3s 3ms/step - loss: -493286858948608.0000 - accuracy: 0.0000e+00 - val_loss: -637913037537280.0000 - val_accuracy: 0.0000e+00
Epoch 6/10
800/800 [==============================] - 3s 3ms/step - loss: -831061609152512.0000 - accurac

In [51]:
regressor.save_weights("regressor.h5")